<?php
// Liste des vols des TV à compter par jour
$tab_TVE = ["LFMRAE", "LFMRAEE", "LFMGYAB", "LFMSBAM", "LFMGY", "LFMAB", "LFMEK"];
$tab_TVW = ["LFMRAW", "LFMMALY", "LFMWW", "LFMMF", "LFMDZ"];
$tab_TVAPP = ["LFKJ","LFKF","LFKB","LFKC","LFKA","LFKO","LFKS","LFMN","LFMD","LFTZ","LFTH","LFML","LFMV","LFMI","LFMY","LFMO","LFMS","LFMZ","LFLI","LFMC","LFMF","LFTF","LFMA","LFMQ","LFLL","LFLY","LFLS","LFLB","LFLP","LFLE","LFLG","LFLJ","LFLM","LFLO","LFLC","LFMH","LFMT","LFTW","LFMP","LFMU","LFLV","LFLN","LFLU","LFNA","LFNB","LFNG","LFNH","LFXA"];
?>